import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { OrdersController } from './orders.controller';
import { OrdersService } from './orders.service';
import {
  ShoppingCart,
  CartItem,
  Checkout,
  Order,
  OrderItem,
  OrderStatusHistory,
  OrderTimeline,
  OrderAddress,
  OrderCoupon,
  OrderDiscount,
  OrderTax,
  OrderPayment,
  OrderInvoice,
  OrderPackage,
  OrderShipment,
  OrderDelivery,
  OrderTracking,
  OrderReturn,
  OrderRefund,
  OrderCancel,
  OrderExchange,
  OrderRating,
  OrderNotification,
  OrderHistory,
  OrderAnalytics,
  OrderReport,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      ShoppingCart,
      CartItem,
      Checkout,
      Order,
      OrderItem,
      OrderStatusHistory,
      OrderTimeline,
      OrderAddress,
      OrderCoupon,
      OrderDiscount,
      OrderTax,
      OrderPayment,
      OrderInvoice,
      OrderPackage,
      OrderShipment,
      OrderDelivery,
      OrderTracking,
      OrderReturn,
      OrderRefund,
      OrderCancel,
      OrderExchange,
      OrderRating,
      OrderNotification,
      OrderHistory,
      OrderAnalytics,
      OrderReport,
    ]),
  ],
  controllers: [OrdersController],
  providers: [OrdersService],
  exports: [OrdersService],
})
export class OrdersModule {}
