import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ReportsController } from './reports.controller';
import { ReportsService } from './reports.service';
import {
  Dashboard,
  DashboardWidget,
  KPI,
  SalesAnalytics,
  RevenueAnalytics,
  CustomerAnalytics,
  AgentAnalytics,
  ReportsRiderAnalytics,
  InventoryAnalytics,
  ProductAnalytics,
  ReportsUsedBookAnalytics,
  DigitalContentAnalytics,
  CustomOrderAnalytics,
  PaymentAnalytics,
  AreaAnalytics,
  VendorAnalytics,
  MarketingAnalytics,
  NotificationAnalytics,
  SearchAnalytics,
  ReportsOrderAnalytics,
  DeliveryAnalytics,
  FinancialAnalytics,
  UserActivityAnalytics,
  ReportTemplate,
  GeneratedReport,
  ScheduledReport,
  ExportHistory,
  Forecast,
  AuditReport,
  BusinessInsight,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Dashboard,
      DashboardWidget,
      KPI,
      SalesAnalytics,
      RevenueAnalytics,
      CustomerAnalytics,
      AgentAnalytics,
      ReportsRiderAnalytics,
      InventoryAnalytics,
      ProductAnalytics,
      ReportsUsedBookAnalytics,
      DigitalContentAnalytics,
      CustomOrderAnalytics,
      PaymentAnalytics,
      AreaAnalytics,
      VendorAnalytics,
      MarketingAnalytics,
      NotificationAnalytics,
      SearchAnalytics,
      ReportsOrderAnalytics,
      DeliveryAnalytics,
      FinancialAnalytics,
      UserActivityAnalytics,
      ReportTemplate,
      GeneratedReport,
      ScheduledReport,
      ExportHistory,
      Forecast,
      AuditReport,
      BusinessInsight,
    ]),
  ],
  controllers: [ReportsController],
  providers: [ReportsService],
  exports: [ReportsService],
})
export class ReportsModule {}
