import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DigitalContentController } from './digital-content.controller';
import { DigitalContentService } from './digital-content.service';
import {
  DigitalContent,
  DigitalCategory,
  DigitalSubCategory,
  DigitalFile,
  DigitalVersion,
  DigitalPreview,
  DigitalAuthor,
  DigitalPublisher,
  DigitalCourse,
  DigitalDepartment,
  DigitalSemester,
  DigitalInstitute,
  DigitalAccess,
  DigitalPurchase,
  DigitalDownload,
  DigitalBookmark,
  DigitalReadingHistory,
  DigitalReview,
  DigitalRating,
  DigitalWishlist,
  DigitalSubscription,
  DigitalCertificate,
  DigitalExam,
  DigitalExamQuestion,
  DigitalExamResult,
  DigitalAnnouncement,
  DigitalFAQ,
  DigitalSEO,
  DigitalAnalytics,
  DigitalReport,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      DigitalContent,
      DigitalCategory,
      DigitalSubCategory,
      DigitalFile,
      DigitalVersion,
      DigitalPreview,
      DigitalAuthor,
      DigitalPublisher,
      DigitalCourse,
      DigitalDepartment,
      DigitalSemester,
      DigitalInstitute,
      DigitalAccess,
      DigitalPurchase,
      DigitalDownload,
      DigitalBookmark,
      DigitalReadingHistory,
      DigitalReview,
      DigitalRating,
      DigitalWishlist,
      DigitalSubscription,
      DigitalCertificate,
      DigitalExam,
      DigitalExamQuestion,
      DigitalExamResult,
      DigitalAnnouncement,
      DigitalFAQ,
      DigitalSEO,
      DigitalAnalytics,
      DigitalReport,
    ]),
  ],
  controllers: [DigitalContentController],
  providers: [DigitalContentService],
  exports: [DigitalContentService],
})
export class DigitalContentModule {}
