import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Area } from '../areas/entities';
import { RidersController } from './riders.controller';
import { RidersService } from './riders.service';
import {
  Rider,
  RiderDocument,
  RiderVehicle,
  RiderArea,
  RiderRoute,
  RiderAvailability,
  RiderShift,
  RiderAttendance,
  RiderAssignment,
  RiderDelivery,
  RiderTracking,
  RiderLocationHistory,
  RiderOTP,
  RiderProof,
  RiderDeliveryAttempt,
  RiderEarning,
  RiderSettlement,
  RiderWallet,
  RiderWalletTransaction,
  RiderPenalty,
  RiderBonus,
  RiderRating,
  RiderPerformance,
  RiderIncident,
  RiderNotification,
  RiderAnnouncement,
  RiderLeave,
  RiderHistory,
  RiderAnalytics,
  RiderReport,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Rider,
      RiderDocument,
      RiderVehicle,
      RiderArea,
      RiderRoute,
      RiderAvailability,
      RiderShift,
      RiderAttendance,
      RiderAssignment,
      RiderDelivery,
      RiderTracking,
      RiderLocationHistory,
      RiderOTP,
      RiderProof,
      RiderDeliveryAttempt,
      RiderEarning,
      RiderSettlement,
      RiderWallet,
      RiderWalletTransaction,
      RiderPenalty,
      RiderBonus,
      RiderRating,
      RiderPerformance,
      RiderIncident,
      RiderNotification,
      RiderAnnouncement,
      RiderLeave,
      RiderHistory,
      RiderAnalytics,
      RiderReport,
      Area,
    ]),
  ],
  controllers: [RidersController],
  providers: [RidersService],
  exports: [RidersService],
})
export class RidersModule {}
