import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CustomOrdersController } from './custom-orders.controller';
import { CustomOrdersService } from './custom-orders.service';
import {
  CustomOrder,
  CustomOrderItem,
  CustomProduct,
  CustomProductTemplate,
  CustomDesign,
  CustomDesignFile,
  CustomSpecification,
  CustomQuotation,
  CustomApproval,
  CustomProduction,
  CustomProductionStage,
  CustomDeliverySchedule,
  GiftCategory,
  GiftProduct,
  GiftBundle,
  GiftBundleItem,
  GiftMessage,
  GiftWrapping,
  GiftOccasion,
  GiftRecipient,
  PrintService,
  PrintJob,
  PrintFile,
  PrintPricing,
  PrintDelivery,
  CustomReview,
  CustomWishlist,
  CustomAnalytics,
  CustomOrderHistory,
  CustomReport,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      CustomOrder,
      CustomOrderItem,
      CustomProduct,
      CustomProductTemplate,
      CustomDesign,
      CustomDesignFile,
      CustomSpecification,
      CustomQuotation,
      CustomApproval,
      CustomProduction,
      CustomProductionStage,
      CustomDeliverySchedule,
      GiftCategory,
      GiftProduct,
      GiftBundle,
      GiftBundleItem,
      GiftMessage,
      GiftWrapping,
      GiftOccasion,
      GiftRecipient,
      PrintService,
      PrintJob,
      PrintFile,
      PrintPricing,
      PrintDelivery,
      CustomReview,
      CustomWishlist,
      CustomAnalytics,
      CustomOrderHistory,
      CustomReport,
    ]),
  ],
  controllers: [CustomOrdersController],
  providers: [CustomOrdersService],
  exports: [CustomOrdersService],
})
export class CustomOrdersModule {}
