import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { FinanceController } from './finance.controller';
import { FinanceService } from './finance.service';
import {
  Company,
  CompanyBranch,
  BankAccount,
  PaymentGateway,
  PaymentTransaction,
  PaymentMethod,
  Wallet,
  WalletTransaction,
  Invoice,
  ExpenseCategory,
  Expense,
  IncomeCategory,
  Income,
  CashFlow,
  JournalEntry,
  Ledger,
  Account,
  Tax,
  Commission,
  Salary,
  Payroll,
  SupplierPayment,
  CustomerRefund,
  FinancialSettlement,
  ProfitLoss,
  BalanceSheet,
  FinancialReport,
  SystemSetting,
  AdminActivity,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Company,
      CompanyBranch,
      BankAccount,
      PaymentGateway,
      PaymentTransaction,
      PaymentMethod,
      Wallet,
      WalletTransaction,
      Invoice,
      ExpenseCategory,
      Expense,
      IncomeCategory,
      Income,
      CashFlow,
      JournalEntry,
      Ledger,
      Account,
      Tax,
      Commission,
      Salary,
      Payroll,
      SupplierPayment,
      CustomerRefund,
      FinancialSettlement,
      ProfitLoss,
      BalanceSheet,
      FinancialReport,
      SystemSetting,
      AdminActivity,
    ]),
  ],
  controllers: [FinanceController],
  providers: [FinanceService],
  exports: [FinanceService],
})
export class FinanceModule {}
