import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CrmController } from './crm.controller';
import { CrmService } from './crm.service';
import {
  CustomerTicket,
  TicketCategory,
  TicketPriority,
  TicketStatus,
  TicketReply,
  TicketAttachment,
  TicketAssignment,
  LiveChat,
  ChatMessage,
  ChatAttachment,
  CustomerFeedback,
  CustomerComplaint,
  CustomerSuggestion,
  FAQ,
  KnowledgeBase,
  Announcement,
  Notification,
  NotificationTemplate,
  EmailQueue,
  SMSQueue,
  PushNotification,
  ContactMessage,
  CustomerSurvey,
  SurveyQuestion,
  SurveyResponse,
  LoyaltyPointHistory,
  CustomerReward,
  CRMActivity,
  CustomerSupportAnalytics,
  CustomerSupportReport,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      CustomerTicket,
      TicketCategory,
      TicketPriority,
      TicketStatus,
      TicketReply,
      TicketAttachment,
      TicketAssignment,
      LiveChat,
      ChatMessage,
      ChatAttachment,
      CustomerFeedback,
      CustomerComplaint,
      CustomerSuggestion,
      FAQ,
      KnowledgeBase,
      Announcement,
      Notification,
      NotificationTemplate,
      EmailQueue,
      SMSQueue,
      PushNotification,
      ContactMessage,
      CustomerSurvey,
      SurveyQuestion,
      SurveyResponse,
      LoyaltyPointHistory,
      CustomerReward,
      CRMActivity,
      CustomerSupportAnalytics,
      CustomerSupportReport,
    ]),
  ],
  controllers: [CrmController],
  providers: [CrmService],
  exports: [CrmService],
})
export class CrmModule {}
