import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { APP_GUARD } from '@nestjs/core';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { AuthModule } from './auth/auth.module';
import { AdminModule } from './admin/admin.module';
import {
  Role,
  Permission,
  PermissionGroup,
  SystemModule,
  RolePermission,
  UserRole,
  UserPermission,
  ApprovalLevel,
  ApprovalWorkflow,
  AuditLog,
  ActivityLog,
  LoginPolicy,
} from './admin/rbac/entities';
import {
  Country,
  Division,
  District,
  Upazila,
  Area,
  AreaCoverage,
  Institute,
  InstituteCampus,
  Department,
  Program,
  Semester,
  AcademicSession,
  StudentInstitute,
  InstituteAgent,
  InstituteDocument,
} from './admin/areas/entities';
import {
  Agent,
  AgentArea,
  AgentInstitute,
  AgentStore,
  AgentEmployee,
  AgentPerformance,
  AgentSalary,
  AgentCommission,
  AgentSettlement,
  AgentWallet,
  AgentWalletTransaction,
  AgentDocument,
  AgentLeave,
  AgentAttendance,
  AgentTarget,
  AgentBonus,
  AgentPenalty,
  AgentAnnouncement,
} from './admin/agents/entities';
import {
  Rider,
  RiderDocument,
  RiderVehicle,
  RiderArea,
  RiderRoute,
  RiderAvailability,
  RiderShift,
  RiderAttendance,
  RiderAssignment,
  RiderDelivery,
  RiderTracking,
  RiderLocationHistory,
  RiderOTP,
  RiderProof,
  RiderDeliveryAttempt,
  RiderEarning,
  RiderSettlement,
  RiderWallet,
  RiderWalletTransaction,
  RiderPenalty,
  RiderBonus,
  RiderRating,
  RiderPerformance,
  RiderIncident,
  RiderNotification,
  RiderAnnouncement,
  RiderLeave,
  RiderHistory,
  RiderAnalytics,
  RiderReport,
} from './admin/riders/entities';
import {
  Warehouse,
  WarehouseZone,
  WarehouseShelf,
  Supplier,
  Purchase,
  PurchaseItem,
  Inventory,
  InventoryBatch,
  StockMovement,
  StockTransfer,
  StockTransferItem,
  StockReservation,
  StockAdjustment,
  StockDamage,
  StockReturn,
  InventoryAudit,
  ReorderRule,
  RestockRequest,
  Barcode,
} from './admin/warehouses/entities';
import {
  AgentShelf,
  AgentInventory,
  AgentInventoryBatch,
  AgentStockMovement,
  AgentStockTransfer,
  AgentStockTransferItem,
  AgentStockReservation,
  AgentRestockRequest,
  AgentRestockItem,
  AgentDamageStock,
  AgentReturnStock,
  AgentInventoryAdjustment,
  AgentInventoryAudit,
  AgentDailySales,
  AgentLowStockAlert,
  AgentProductReceive,
  AgentStoreExpense,
  AgentStoreExpenseCategory,
  AgentStoreClosing,
} from './admin/inventory/entities';
import {
  Product,
  ProductCategory,
  ProductSubCategory,
  ProductBrand,
  ProductVariant,
  ProductVariantOption,
  ProductAttribute,
  ProductAttributeValue,
  ProductImage,
  ProductGallery,
  ProductPrice,
  ProductCost,
  ProductInventory,
  ProductBarcode,
  ProductTag,
  ProductReview,
  ProductRating,
  ProductFAQ,
  ProductSEO,
  ProductBundle,
  ProductBundleItem,
  ProductRecommendation,
  ProductViewHistory,
  ProductWishlist,
  ProductComparison,
} from './admin/products/entities';
import {
  Book,
  BookEdition,
  BookAuthor,
  BookPublisher,
  BookCategory,
  BookSubject,
  BookLanguage,
  BookSeries,
  BookCourse,
  BookSemester,
  BookDepartment,
  BookInstitute,
  BookCondition,
  BookTag,
  BookFile,
  BookPreview,
  BookRecommendation,
  BookReview,
  BookFavorite,
  BookReadingList,
  BookPriceHistory,
} from './admin/books/entities';
import { StrictJwtAuthGuard } from './auth/guards/strict-jwt-auth.guard';
import {
  User,
  UserProfile,
  StudentProfile,
  UserAddress,
  UserDevice,
  UserSession,
  UserOTP,
  UserToken,
  UserLoginHistory,
  UserSecurity,
  UserPreference,
  UserNotificationSetting,
  UserIdentityVerification,
  UserAttachment,
  UserActivity,
  SupportTicket,
} from './auth/entities';

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        type: 'postgres',
        url: configService.get<string>('DATABASE_URL'),
        ssl: {
          rejectUnauthorized: false,
        },
        entities: [
          User,
          UserProfile,
          StudentProfile,
          UserAddress,
          UserDevice,
          UserSession,
          UserOTP,
          UserToken,
          UserLoginHistory,
          UserSecurity,
          UserPreference,
          UserNotificationSetting,
          UserIdentityVerification,
          UserAttachment,
          UserActivity,
          SupportTicket,
          Role,
          Permission,
          PermissionGroup,
          SystemModule,
          RolePermission,
          UserRole,
          UserPermission,
          ApprovalLevel,
          ApprovalWorkflow,
          AuditLog,
          ActivityLog,
          LoginPolicy,
          Country,
          Division,
          District,
          Upazila,
          Area,
          AreaCoverage,
          Institute,
          InstituteCampus,
          Department,
          Program,
          Semester,
          AcademicSession,
          StudentInstitute,
          InstituteAgent,
          InstituteDocument,
          Agent,
          AgentArea,
          AgentInstitute,
          AgentStore,
          AgentEmployee,
          AgentPerformance,
          AgentSalary,
          AgentCommission,
          AgentSettlement,
          AgentWallet,
          AgentWalletTransaction,
          AgentDocument,
          AgentLeave,
          AgentAttendance,
          AgentTarget,
          AgentBonus,
          AgentPenalty,
          AgentAnnouncement,
          Rider,
          RiderDocument,
          RiderVehicle,
          RiderArea,
          RiderRoute,
          RiderAvailability,
          RiderShift,
          RiderAttendance,
          RiderAssignment,
          RiderDelivery,
          RiderTracking,
          RiderLocationHistory,
          RiderOTP,
          RiderProof,
          RiderDeliveryAttempt,
          RiderEarning,
          RiderSettlement,
          RiderWallet,
          RiderWalletTransaction,
          RiderPenalty,
          RiderBonus,
          RiderRating,
          RiderPerformance,
          RiderIncident,
          RiderNotification,
          RiderAnnouncement,
          RiderLeave,
          RiderHistory,
          RiderAnalytics,
          RiderReport,
          Warehouse,
          WarehouseZone,
          WarehouseShelf,
          Supplier,
          Purchase,
          PurchaseItem,
          Inventory,
          InventoryBatch,
          StockMovement,
          StockTransfer,
          StockTransferItem,
          StockReservation,
          StockAdjustment,
          StockDamage,
          StockReturn,
          InventoryAudit,
          ReorderRule,
          RestockRequest,
          Barcode,
          AgentShelf,
          AgentInventory,
          AgentInventoryBatch,
          AgentStockMovement,
          AgentStockTransfer,
          AgentStockTransferItem,
          AgentStockReservation,
          AgentRestockRequest,
          AgentRestockItem,
          AgentDamageStock,
          AgentReturnStock,
          AgentInventoryAdjustment,
          AgentInventoryAudit,
          AgentDailySales,
          AgentLowStockAlert,
          AgentProductReceive,
          AgentStoreExpense,
          AgentStoreExpenseCategory,
          AgentStoreClosing,
          Product,
          ProductCategory,
          ProductSubCategory,
          ProductBrand,
          ProductVariant,
          ProductVariantOption,
          ProductAttribute,
          ProductAttributeValue,
          ProductImage,
          ProductGallery,
          ProductPrice,
          ProductCost,
          ProductInventory,
          ProductBarcode,
          ProductTag,
          ProductReview,
          ProductRating,
          ProductFAQ,
          ProductSEO,
          ProductBundle,
          ProductBundleItem,
          ProductRecommendation,
          ProductViewHistory,
          ProductWishlist,
          ProductComparison,
          Book,
          BookEdition,
          BookAuthor,
          BookPublisher,
          BookCategory,
          BookSubject,
          BookLanguage,
          BookSeries,
          BookCourse,
          BookSemester,
          BookDepartment,
          BookInstitute,
          BookCondition,
          BookTag,
          BookFile,
          BookPreview,
          BookRecommendation,
          BookReview,
          BookFavorite,
          BookReadingList,
          BookPriceHistory,
        ],
        synchronize: true,
      }),
    }),
    AuthModule,
    AdminModule,
  ],
  controllers: [AppController],
  providers: [
    AppService,
    // Enable Global Strict Auth Guard: EVERY endpoint is protected by default unless decorated with @Public()
    {
      provide: APP_GUARD,
      useClass: StrictJwtAuthGuard,
    },
  ],
})
export class AppModule {}
